services:
  pipboy-test:
    image: pipboy-test
    container_name: pipboy_test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./source/lib:/home/app/app/lib
      - ./test:/home/app/app/test
