services:
  pipboy-test:
    image: pipboy-test
    container_name: pipboy_test
    user: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./test:/home/app/app/
      - ./pipboy:/home/app/app/lib
