version: 2

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: gcc
    working_directory: /root/project/test
    steps:
      - checkout:
          path: /root/project
      - run:
          name: Copy files
          command: cp ../source/lib ./lib -R
      - run:
          name: Generate binary
          command: make
      - run:
          name: Run tests
          command: make run
