version: 2

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: gcc
    steps:
      - checkout
      - run:
          name: Set working directory
          command: cd test
      - run:
          name: LS
          command: ls
