version: 2

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: gcc
    working_directory: /root/project/test
    steps:
      - checkout:
          path: /root/project
      - run:
          name: DEBUG
          command: pwd
      - run:
          name: LS
          command: ls
