version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: circleci/cpp
    steps:
      echo:
        name: Echo
        command: echo ok
