version: 2

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: cpp
    steps:
      - echo:
        name: Echo
        command: echo ok
